all:
			g++ -c main.cpp
			g++ -c escritura.cpp
			g++ -c interfaz.cpp
			g++ -c opbasic.cpp
			g++ -c raices.cpp
			g++ -c porcentajes.cpp
			g++ -c potencias.cpp
			g++ -o pascalina potencias.o porcentajes.o raices.o opbasic.o interfaz.o escritura.o main.o

